import Head from 'next/head'
import Appnav from '../components/organism/Appnav'
import { Box, Button, Container, Grid, Paper, Stack, Typography } from '@mui/material'
import Image from 'next/image'
import GroupsRoundedIcon from '@mui/icons-material/GroupsRounded';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import PermMediaRoundedIcon from '@mui/icons-material/PermMediaRounded';
import Link from 'next/link';
import EventCarousel from '../components/organism/EventCarousel';
import DaisyCarousel from '../components/organism/DaisyCarousel';
import EventCalendar from '../components/organism/EventCalendar';
import EventDynamic from '../components/organism/EventDynamic';
import PengumumanContent from '../components/organism/PengumumanContent';
import Footer from '../components/organism/Footer';
import UpdatesNotification from '../components/organism/UpdatesNotification';
import ContainerPage from '../components/atoms/ContainerPage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Halaman Beranda - Sistem Informasi Manajemen Pelayanan dan Berita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className='bg-white'> 
        <UpdatesNotification />
        <Box className='w-screen h-[80vh] relative'>
          <Appnav />
          <Image src='/images/hero-5.jpg' alt="Hero's Site" layout='fill' objectFit='cover' className='pt-0 brightness-[0.3]'/>
        </Box>
          <ContainerPage>
          <Paper variant='outlined' className='-translate-y-14 xs:-translate-y-9 shadow-lg rounded-xl p-5 px-4'>
            <Grid container spacing={2} className='px-5'>
              <Grid item xs={4}>
                <Link href="/" className='grid place-items-center align-middle hover:brightness-125'>
                  <GroupsRoundedIcon color='primary' sx={{ fontSize: { xs: 50, md: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center' sx={{display: {xs: 'none', md: 'block'}}}>Layanan Hubungan Masyarakat</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/' className='grid place-items-center align-middle hover:brightness-125'>
                  <CloudUploadIcon color='primary' sx={{ fontSize: { xs: 50, md: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center'sx={{display: {xs: 'none', md: 'block'}}}>Layanan Publikasi</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/' className='grid place-items-center align-middle hover:brightness-125'>
                  <PermMediaRoundedIcon color='primary' sx={{ fontSize: { xs: 50, md: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center'sx={{display: {xs: 'none', md: 'block'}}}>Layanan Media</Typography>
                </Link>
              </Grid>
            </Grid>
          </Paper>
          {/* <Paper variant='outlined' className='shadow-md rounded-xl p-5 px-4'> */}
            <Grid container spacing={2}>
              <Grid item xs={12} md={5}>
                <Stack spacing={2}>
                  <Typography variant='h5' className='font-bold mb-2' color='primary'>Kalendar Agenda</Typography>
                  <Box className='justify-center flex'>
                    <EventCalendar />
                    {/* <EventtCalendar /> */}
                    {/* <EventDynamic /> */}
                  </Box>
                </Stack>
              </Grid>
              <Grid item xs={12} md={7}>
                {/* <EventCarousel /> */}
                <Box>
                  <Typography variant='h5' className='font-bold mb-2' color='primary'>Agenda Terkini</Typography>
                  <Box className='justify-center flex'>
                    <DaisyCarousel />
                  </Box>
                  <Box className='flex justify-center mt-6 mb-10'>
                    <Link href='/events'>
                      <Button variant='outlined' color='primary' size='small' className='rounded-lg capitalize'>Lihat Lainnya</Button>
                    </Link>
                  </Box>

                </Box>
              </Grid>
            </Grid>
            <Box className='mt-4'>
              <Typography variant='h5' className='font-bold mb-6' color='primary'>Pengumuman Sistem</Typography>
              <Grid container spacing={2} className='my-4 -mx-1'>
                <PengumumanContent />
              </Grid>
              <Box className='flex justify-center mb-8'>
                <Button variant='outlined' color='primary' size='medium' className='capitalize rounded-lg'>Lihat Lainnya</Button>
              </Box>
            </Box>
          {/* </Paper> */}
        </ContainerPage>
        <Footer />
      </Box>
    </>
  )
}
