import Head from 'next/head'
import Appnav from '../components/organism/Appnav'
import { Box, Container, Grid, Paper, Stack, Typography } from '@mui/material'
import Image from 'next/image'
import GroupsRoundedIcon from '@mui/icons-material/GroupsRounded';
import CloudUploadIcon from '@mui/icons-material/CloudUpload';
import PermMediaRoundedIcon from '@mui/icons-material/PermMediaRounded';
import Link from 'next/link';
import EventCarousel from '../components/organism/EventCarousel';
import DaisyCarousel from '../components/organism/DaisyCarousel';
import EventCalendar from '../components/organism/EventCalendar';
import EventDynamic from '../components/organism/EventDynamic';

export default function Home() {
  return (
    <>
      <Head>
        <title>Halaman Beranda - Sistem Informasi Manajemen Pelayanan dan Berita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className='w-screen h-[80vh] relative'>
        <Appnav />
        <Image src='/images/hero-5.jpg' alt="Hero's Site" layout='fill' objectFit='cover' className='pt-0 brightness-[0.3]'/>
      </Box>      
      <Box className='bg-white pb-20'>
        <Container sx={{width: {xs: 380, sm: 760, lg: 1280}}}>
          <Paper variant='outlined' className='-translate-y-14 xs:-translate-y-9 shadow-lg rounded-xl p-5 px-4'>
            <Grid container spacing={2} className='px-5'>
              <Grid item xs={4}>
                <Link href="/" className='grid place-items-center align-middle hover:brightness-125'>
                  <GroupsRoundedIcon color='primary' sx={{ fontSize: { xs: 50, sm: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center' sx={{display: {xs: 'none', sm: 'block'}}}>Layanan Hubungan Masyarakat</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/' className='grid place-items-center align-middle hover:brightness-125'>
                  <CloudUploadIcon color='primary' sx={{ fontSize: { xs: 50, sm: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center'sx={{display: {xs: 'none', sm: 'block'}}}>Layanan Publikasi</Typography>
                </Link>
              </Grid>
              <Grid item xs={4}>
                <Link href='/' className='grid place-items-center align-middle hover:brightness-125'>
                  <PermMediaRoundedIcon color='primary' sx={{ fontSize: { xs: 50, sm: 40} }}/>
                  <Typography variant='h6' className='font-bold text-center'sx={{display: {xs: 'none', sm: 'block'}}}>Layanan Media</Typography>
                </Link>
              </Grid>
            </Grid>
          </Paper>
        </Container>
        <Container sx={{width: {xs: 380, sm: 760, lg: 1280}}}>
          <Paper variant='outlined' className='shadow-md rounded-xl p-5 px-4'>
            <Grid container spacing={2}>
              <Grid item xs={12} md={5}>
                <Stack spacing={2}>
                  <Typography variant='h5' className='font-bold mb-2' color='primary'>Kalendar Agenda</Typography>
                  <Box className='justify-center flex'>
                    <EventCalendar />
                    {/* <EventtCalendar /> */}
                    {/* <EventDynamic /> */}
                  </Box>
                </Stack>
              </Grid>
              <Grid item xs={12} md={7}>
                {/* <EventCarousel /> */}
                <Box>
                  <Typography variant='h5' className='font-bold mb-2' color='primary'>Agenda Terkini</Typography>
                  <DaisyCarousel />
                </Box>
              </Grid>
            </Grid>
          </Paper>
        </Container>
      </Box>
    </>
  )
}
